"""Compara el conteo del sistema contra tu conteo manual.

Los nombres de las direcciones salen de config.json, asi que funciona
igual si les pusiste entrada/salida o izq_a_der/der_a_izq.

Llena validacion.csv con los tramos que contaste a mano.
"""

# Libraries used by the program:
# argparse -> allows us to use command-line arguments such as --por-minuto
# csv     -> reads the CSV files
# json    -> reads config.json
# os      -> checks if files exist
# sys     -> allows the program to stop with an error message
# Counter -> counts how many events belong to each direction
import argparse
import csv
import json
import os
import sys
from collections import Counter


# Default location of the automatic counting results.
CONTEO = "salida/conteo.csv"

# Default file containing the manual count.
VALIDACION = "validacion.csv"


# Reads the names of the two directions from config.json.
def nombres(ruta="config.json"):
    try:
        # Open the configuration file.
        with open(ruta) as f:

            # Convert the JSON file into a Python dictionary.
            cfg = json.load(f)

        # Get the positive and negative direction names.
        # If they don't exist, use "entrada" and "salida".
        return (cfg.get("direccion_positiva", "entrada"),
                cfg.get("direccion_negativa", "salida"))

    # If config.json doesn't exist or contains invalid JSON,
    # use the default names instead of crashing.
    except (OSError, json.JSONDecodeError):
        return "entrada", "salida"


# Reads the events generated by the automatic counting system.
def leer_eventos(ruta):

    # Check whether the CSV file exists.
    if not os.path.exists(ruta):

        # Stop the program and tell the user what needs to be done.
        sys.exit(f"Falta {ruta}. Corre primero: python contador.py")

    # Open the automatic counting CSV.
    with open(ruta) as f:

        # DictReader converts every CSV row into a dictionary.
        return [
            {
                # Convert the second to a decimal number.
                "segundo": float(r["segundo"]),

                # Store the detected direction.
                "direccion": r["direccion"],

                # Convert the tracking ID to an integer.
                "track_id": int(r["track_id"])
            }
            for r in csv.DictReader(f)
        ]


# Counts events that occurred between "inicio" and "fin".
def contar_en(eventos, inicio, fin):

    # Counter groups the events by their direction.
    # The condition selects only events inside the requested time interval.
    return Counter(
        e["direccion"]
        for e in eventos
        if inicio <= e["segundo"] < fin
    )


# Calculates how close the system count is to the manual count.
def exactitud(sistema, real):

    # Special case: there were actually zero people.
    if real == 0:

        # If the system also counted zero, accuracy is 100%.
        # Otherwise, accuracy is 0%.
        return 100.0 if sistema == 0 else 0.0

    # Calculate the percentage based on the difference
    # between the automatic and manual counts.
    return max(
        0.0,
        100.0 * (1 - abs(sistema - real) / real)
    )


# Creates the initial template for validacion.csv.
def plantilla(pos, neg):

    # The CSV contains the time interval and the manual
    # count for both directions.
    return (
        f"# tramos que contaste a mano. positivas={pos}, negativas={neg}\n"
        "inicio_s,fin_s,positivas_reales,negativas_reales\n"
        "0,300,0,0\n"
    )


# Displays the automatic count separated by minute.
def tabla_por_minuto(eventos, pos, neg):

    # If there are no events, there is nothing to display.
    if not eventos:
        return

    # Find the last minute that contains an event.
    ultimo = int(max(e["segundo"] for e in eventos) // 60) + 1

    print("\nCruces por minuto\n")

    # Print the table headers.
    print(f"  {'min':>4}  {pos:>12}  {neg:>12}")

    # Go through every minute.
    for m in range(ultimo):

        # Count events occurring during this minute.
        c = contar_en(eventos, m * 60, (m + 1) * 60)

        # Get the number of positive and negative crossings.
        a, b = c.get(pos, 0), c.get(neg, 0)

        # Display the results.
        print(f"  {m:>4}  {a:>12}  {b:>12}  {'#' * a}")


# Main function: controls the complete validation process.
def main():

    # Create the command-line argument parser.
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    # Allow the user to specify a different automatic-count file.
    p.add_argument("--conteo", default=CONTEO)

    # Allow the user to specify a different manual-validation file.
    p.add_argument("--validacion", default=VALIDACION)

    # Allow the user to specify a different configuration file.
    p.add_argument("--config", default="config.json")

    # Optional flag that displays results grouped by minute.
    p.add_argument("--por-minuto", action="store_true")

    # Read the arguments supplied when running the program.
    args = p.parse_args()


    # Get the names of the two directions from config.json.
    pos, neg = nombres(args.config)

    # Load all automatically detected crossing events.
    eventos = leer_eventos(args.conteo)


    # Get all direction names found in the CSV.
    vistas = {e["direccion"] for e in eventos}

    # Check whether the CSV contains unexpected direction names.
    if vistas - {pos, neg}:

        # Warn the user instead of silently producing incorrect results.
        print(
            f"AVISO: {args.conteo} tiene direcciones {sorted(vistas)}, pero "
            f"{args.config} dice ('{pos}', '{neg}')."
        )

        print(
            "       Vuelve a correr contador.py, "
            "o pasa el config correcto.\n"
        )


    # Count the total number of automatic events for each direction.
    total = Counter(e["direccion"] for e in eventos)

    # Display the automatic totals and the number of different tracked people.
    print(
        f"Sistema: {total.get(pos, 0)} {pos}, "
        f"{total.get(neg, 0)} {neg}, "
        f"{len({e['track_id'] for e in eventos})} personas distintas"
    )


    # If --por-minuto was specified, display the minute-by-minute table.
    if args.por_minuto:
        tabla_por_minuto(eventos, pos, neg)


    # Check whether the manual validation file exists.
    if not os.path.exists(args.validacion):

        # If it doesn't exist, create a template.
        with open(args.validacion, "w") as f:
            f.write(plantilla(pos, neg))

        # Tell the user to manually count the video and fill the template.
        print(
            f"\nCree la plantilla {args.validacion}. "
            "Cuenta a mano un tramo del"
        )
        print(
            "video, llena los numeros reales y vuelve a correr esto."
        )

        # Stop because there is no manual data to compare yet.
        return


    # Open the manual validation CSV.
    with open(args.validacion) as f:

        # Ignore lines beginning with "#".
        # DictReader converts each remaining row into a dictionary.
        tramos = [
            r for r in csv.DictReader(
                l for l in f if not l.startswith("#")
            )
        ]


    # Print the table headers for the comparison.
    print(
        f"\n{'tramo':>14}  {'sis':>5} {'real':>5} {'err':>5}  "
        f"{'sis':>5} {'real':>5} {'err':>5}"
    )

    print(f"{'':>14}  {pos:^17}  {neg:^17}")
    print("  " + "-" * 58)


    # Variables used to accumulate the totals.
    # sp/rp -> system/real positive counts
    # sn/rn -> system/real negative counts
    sp = rp = sn = rn = 0


    # Process every manually defined time interval.
    for t in tramos:

        # Get the beginning and end of the interval.
        ini = float(t["inicio_s"])
        fin = float(t["fin_s"])

        # Count automatic events inside this interval.
        c = contar_en(eventos, ini, fin)

        # Automatic positive count vs manual positive count.
        a = c.get(pos, 0)
        ra = int(t["positivas_reales"])

        # Automatic negative count vs manual negative count.
        b = c.get(neg, 0)
        rb = int(t["negativas_reales"])

        # Add this interval's numbers to the totals.
        sp += a
        rp += ra
        sn += b
        rn += rb

        # Display:
        # system count | manual count | difference
        # for both directions.
        print(
            f"{ini:>6.0f}-{fin:<7.0f}  "
            f"{a:>5} {ra:>5} {a - ra:>+5}  "
            f"{b:>5} {rb:>5} {b - rb:>+5}"
        )


    # Print the separator and the total comparison.
    print("  " + "-" * 58)

    print(
        f"{'TOTAL':>14}  "
        f"{sp:>5} {rp:>5} {sp - rp:>+5}  "
        f"{sn:>5} {rn:>5} {sn - rn:>+5}"
    )


    # Calculate and display the accuracy for the positive direction.
    print(
        f"\n  Exactitud en {pos}: "
        f"{exactitud(sp, rp):.1f}%"
    )

    # Calculate and display the accuracy for the negative direction.
    print(
        f"  Exactitud en {neg}: "
        f"{exactitud(sn, rn):.1f}%"
    )


    # Important limitation:
    # the program compares totals in each time interval,
    # not whether the exact same person was detected correctly.
    print("\n  Nota: esto compara totales por tramo, no persona por persona.")

    # A false positive and a false negative can cancel each other out
    # when only totals are compared.
    print("  Un falso positivo y un falso negativo se cancelan entre si.")


# Only execute main() when this file is run directly.
# For example: python validar.py
if __name__ == "__main__":
    main()